test: Fix provisioning tests by not trying to remove google-cloud-sdk
We're seeing intermittent provisioning failures with this message:

```
No apt package "google-cloud-sdk", but there is a snap with that name.
Try "snap install google-cloud-sdk"

E: Unable to locate package google-cloud-sdk
Error: Process completed with exit code 100.
```

I couldn't figure out why, but all we care about is that there's enough
disk space, so it's probably fine to just not bother with trying to remove
it.